#!/usr/bin/env bash

case "$1" in
  job_assistant | j)
    cd /mnt/c/Programming_WSL/Git_repos/job_assistant
    git branch && git status && code ./
    ;;

  js-30 | 30)
    cd /mnt/c/Programming_WSL/Git_repos/JS_30_challenge
    git branch && git status && code ./
    ;;
  useful-repo | u)
    cd /mnt/c/Programming_WSL/Git_repos/Useful_shells_configs
    git branch && git status && code ./
    ;;
  *)
    cat run_ex_help.txt
esac
